package cd0522.data;

import java.time.LocalDate;

import cd0522.enums.*;
import static cd0522.util.ApplicationConstants.dateFormat;
import lombok.Builder;
import lombok.Data;

/**
 * The rental agreement to be generated by the checkout.
 */
@Data
@Builder
public class RentalAgreement {
    private ToolCode toolCode;
    private ToolType toolType;
    private ToolBrand toolBrand;
    private int rentalDays;
    private LocalDate checkoutDate;
    private LocalDate dueDate;
    private double dailyRentalCharge;
    private int chargeDays;
    private double prediscountCharge;
    private int discountPercent;
    private double discountAmount;
    private double finalCharge;

    @Override
    public String toString() {
        return String.format(
                "Tool code: %s\n" + "Tool type: %s\n" + "Tool brand: %s\n" + "Rental days: %d\n"
                        + "Checkout date: %s\n" + "Due date: %s\n" + "Daily rental charge: $%,.2f\n"
                        + "Charge days: %d\n" + "Prediscount charge: $%,.2f\n"
                        + "Discount percent: %d%%\n" + "Discount amount: $%,.2f\n"
                        + "Final charge: $%,.2f",
                toolCode, toolType, toolBrand, rentalDays, checkoutDate.format(dateFormat),
                dueDate.format(dateFormat), dailyRentalCharge, chargeDays, prediscountCharge,
                discountPercent, discountAmount, finalCharge);
    }
}
